import type { Metadata } from "next";
import { Box, Flex, Heading } from "@chakra-ui/react";
import { PermissionNav } from "@/components/permission-nav";
import { InviteModal } from "@/components/invite-modal";
import GetUserRoles from "@/components/common/GetUserRoles";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Flex p={"24px"} gap={"18px"} direction={"column"}>
        <Box bg={"white"} borderRadius={"12px"}>
          <Flex
            mt={"12px"}
            p={"24px"}
            justify={"space-between"}
            align={"center"}
          >
            <Heading
              as={"h4"}
              fontWeight={"600"}
              fontSize={{ md: "24px", base: "20px" }}
              alignItems={"flex-start"}
            >
              Permissions
            </Heading>
            <InviteModal />
          </Flex>

          <PermissionNav />
          {children}
        </Box>
      </Flex>
      <GetUserRoles />
    </>
  );
}
