import { Box, Image, Text } from "@chakra-ui/react";
import BackButton from "@/components/common/Back";
import "./Generator.css";
import { getGeneratorTypes } from "@/actions/generator";
import { AIContractForm } from "@/components/generator/AIContractForm";
import { authOptions } from "@/types/nextauth.config";
import { getServerSession } from "next-auth";

export type QuestionType = {
    id: number;
    name: string;
};

export default async function Generator() {
    const session = await getServerSession(authOptions);

    const questionTypes: QuestionType[] = await getGeneratorTypes(
        session?.tokens?.access || ""
    );

    return (
        <Box
            borderRadius={"12px"}
            minHeight="100vh"
            display="flex"
            flexDirection="column"
        >
            <nav
                style={{
                    display: "flex",
                    justifyContent: "space-between",
                    background: "#FFFFFF",
                }}
            >
                <Box
                    className="left-side"
                    style={{
                        display: "flex",
                        alignItems: "center",
                        width: "100%",
                    }}
                    gap={{ base: "10px", sm: "0" }}
                    padding={{ sm: "0", md: "20px 10px", lg: "20px 40px" }}
                >
                    <Image
                        width={{ lg: "42px", md: "42px", sm: "16px" }}
                        display={{ base: "none", md: "inline-block" }}
                        src={"/images/short-logo.svg"}
                        alt={"brand logo"}
                    />
                    <BackButton />
                    <Text
                        fontSize={{ sm: "sm", md: "lg", lg: "lg" }}
                        whiteSpace={"nowrap"}
                        overflow={"hidden"}
                        textOverflow={"ellipsis"}
                        paddingLeft={{ sm: "4px", md: "6px", lg: "6px" }}
                        width={{ sm: "50%", md: "auto", lg: "auto" }}
                    >
                        Generated by AI
                    </Text>
                </Box>
            </nav>

            <AIContractForm questionTypes={questionTypes} />
        </Box>
    );
}
