import type { Metadata } from "next";
import "@/styles/global.scss";
import ChakraProviders from "@/hooks/ChakraProviders";
import SessionProviders from "@/hooks/SessionProviders";
import RecoilProviders from "@/hooks/RecoilProviders";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  return (
    <html lang={locale}>
      <ChakraProviders>
        <SessionProviders>
          <RecoilProviders>
            <body>{children}</body>
          </RecoilProviders>
        </SessionProviders>
      </ChakraProviders>
    </html>
  );
}
